# Generated by Django 5.0.2 on 2025-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectionsScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_score_details", models.TextField()),
                ("player_name", models.CharField(max_length=100)),
                ("puzzle_number", models.IntegerField(blank=True, null=True)),
                ("score_details", models.TextField()),
                ("score_value", models.IntegerField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "score_comment",
                    models.CharField(blank=True, default="", max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
